controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

urlRedirects:
    path: /{code}
    defaults: {_controller: 'App\Controller\DefaultController'}
    requirements:
        code: '[A-Za-z0-9]{7,}'